version: '3'
services:
  As:
    image: as-hegemony
    build: generic/detector
    environment:
      - CRONTAB="0 0 * * *"
    volumes:
      - ./generic/detector/hegemonydetector.conf:/conf/detector.conf

  Atlas:
    image: atlas-delay
    build: generic/detector
    environment:
      - CRONTAB="0 0 * * *"
    volumes:
      - ./generic/detector/atalasdetector.conf:/conf/detector.conf

